---
tomcat7_home: "{{ inera_root }}/tomcat7"
tomcat7_version: 7.0.62
tomcat_user: inera-tomcat
tomcat_group: inera-tomcat
tomcat_service: inera-tomcat

tomcat_version: "{{ tomcat7_version }}"
tomcat_home: "{{ tomcat7_home }}"

catalina_home: "{{ tomcat_home }}"
catalina_base: "{{ tomcat_home }}"

tomcat_download_url:  http://apache.mirrors.spacedump.net/tomcat/tomcat-7/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz

# Konto för tomcat admin-gui
admin_username: 
admin_password: 
