---

- name: add yum mongo repo
  when: ansible_os_family == "RedHat"
  ini_file: dest=/etc/yum.repos.d/mongodb.repo
            section=mongodb
            state=present
            option="{{ item.key }}"
            value="{{ item.value }}"
  with_dict:
    name: "MongoDB Repository"
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    gpgcheck: 0
    enabled: 1

